### ISSUE TITLE
Sign up form

### ISSUE THREAD

**Issue by Qwerios** [mufty/interesting-bot#20]
We need to add at least links to the raid and guild ethos. This is a fair amount of text but people that want to apply are interested in that text.

Once an application is made we also need a way to interact with the applicant much like Enjin form comments work.

It could be an option to replace the current form with an apply now button and work on a separate page (or better ready made system). Mike mentioned Google Forms and I know I can make some custom stuff with Firebase. Truth be told I don't know if I have enough time to cobble up so me firebase thingie.

What could be done with Firebase is a per applicant page using firebase auth to link it to them. So when they click apply they would go to the signup page/app which asks them to authenticate with whatever OAuth account they want (google, facebook, etc). That limits to the page to them. Use admins will be authorised for the applicant list page and we can reach each application. On that page I could impelement a simple post board kind of thing. I'd recommend application admin comments to be done on Discord.

Google Forms would be great because its ready made. I just dont know if there is a post submit feedback option. Something to look into. Google Forms can be embedded with an iframe so could be placed right into the page

**Comment by mufty** [comment]
I don't think there is a possibility to reply to an applicant when using Google Form unless they use an email that they actively use. We could reply via emails or RealID.

**Comment by mufty** [comment]
First thing we should try to use something already made for the application form that is why I'm still keen on using Google Form. Unless it proves to be too much of work. Doing custom form with replies, discussion, notifications and all that stuff might be too much.

**Comment by Qwerios** [comment]
Would it work if we use google forms and on the success page provide people with a discord invite link on successful submission? We pretty much will be requiring discord anyway. Then we can text chat with the applicant through discord and give them a role on successful app or uninvite them on decline.

**Comment by Qwerios** [comment]
Just checked googel forms allows you to come back and edit the form apparently. Restricting to only 1 submission requires logging in with google which might be a bit of a barrier.

**Comment by Qwerios** [comment]
I've deployed a new version with an ethos/guidelines page:
https://interesting-times-bot.firebaseapp.com/ethos.html

Might have to reload to fix CSS issues. I had some sticky cache.

I've also setup a google forms for the application form thing. It will send an email to all collaborators on the form and responses will be managed through google forms. People who submit can go back and edit their application apparently.

I think this is a pretty nice minimal effort setup. Might be an idea to consider adding a discord join link in the submission success text.

**Comment by Qwerios** [comment]
@mufty I've sent you an invite to see and edit the google form

**Comment by mufty** [comment]
https://discord.gg/w6Uec6r

**Comment by Qwerios** [comment]
I think we can safely call this feature implemented. We can update graphics and styling at any time.
